"""The artifact the developer actually receives.

Rendered deterministically from state the workflow already holds -- the verifier's findings,
what the repair step changed, and the tests that shipped with the ticket. No extra model call,
so the report cannot drift from what the run actually did.

The report never claims the code is correct. It says what was checked, what was fixed, and --
the part that matters to someone with no second reviewer -- what remains unproven.
"""
from __future__ import annotations

import os


def _bullet(finding: dict) -> str:
    return (
        "- **%s** (%s)\n"
        "  - Requirement: %s\n"
        "  - Evidence: %s\n"
        "  - If shipped: %s\n"
        % (
            finding.get("title", "(untitled)"),
            finding.get("severity", "unrated"),
            finding.get("requirement", "not stated by the reviewer"),
            finding.get("evidence", "not stated"),
            finding.get("failure", "not stated"),
        )
    )


def render(case_id: str, ticket_title: str, result: dict, score: dict) -> str:
    initial = result.get("findings_initial")
    final = result.get("findings_final")

    initial_list = initial or []
    final_list = final or []
    gate_info = result.get("gate") or {}
    advisory = result.get("advisory_findings") or []

    lines = []
    lines.append("# Production readiness report — %s" % ticket_title)
    lines.append("")
    lines.append("Case `%s`. Generated by the verify/repair workflow. "
                 "**This is a recommendation, not an approval.**" % case_id)
    lines.append("")

    # --- headline -------------------------------------------------------------------
    visible = "%d/%d" % (score.get("visible_passed", 0), score.get("visible_total", 0))
    if final is None or initial is None:
        recommendation = "Needs a human read — the review did not complete cleanly"
    elif final_list:
        recommendation = "Ready for developer review — %d issue(s) still flagged" % len(final_list)
    else:
        recommendation = "Ready for developer review — nothing still flagged"

    lines.append("**Recommendation:** %s  " % recommendation)
    lines.append("**Tests shipped with the ticket:** %s passing  " % visible)
    if initial is not None:
        lines.append("**Raised by the first review:** %d  " % len(initial_list))
    if final is not None:
        lines.append("**Still flagged after repair:** %d  " % len(final_list))
    if gate_info:
        lines.append("**Repaired under evidence gate:** %d  " % gate_info.get("demonstrated", 0))
        lines.append("**Flagged for you, not acted on:** %d  " % gate_info.get("advisory", 0))
        if gate_info.get("repair_reverted"):
            lines.append("**A repair was reverted** — it cost a test that shipped with the "
                         "ticket.  ")
    lines.append("**Action:** the developer reviews the patch and decides whether to ship it.")
    lines.append("")

    # --- what was found and fixed ---------------------------------------------------
    lines.append("## What review found")
    lines.append("")
    if initial is None:
        lines.append("The reviewer did not return a parseable result. Nothing was verified "
                     "automatically; treat this change as unreviewed.")
    elif not initial_list:
        lines.append("Nothing. The reviewer read the implementation against the requirements it "
                     "should be held to and raised no issue. That is a weaker statement than "
                     "'this is correct' — see *Still unproven*.")
    else:
        lines.append("### Raised by the first review, and sent to repair")
        lines.append("")
        for f in initial_list:
            lines.append(_bullet(f))
        lines.append("")
        lines.append("### Still flagged after the repair pass")
        lines.append("")
        if final is None:
            lines.append("The re-review did not return a parseable result, so nothing here has "
                         "been confirmed fixed.")
        elif not final_list:
            lines.append("Nothing.")
        else:
            for f in final_list:
                lines.append(_bullet(f))
        lines.append("")
        lines.append("> The two lists are **not** a before/after mapping. Each review names its "
                     "own findings independently, so an item missing from the second list may "
                     "have been fixed, or may simply not have been raised again. Read the second "
                     "list as the current state, not as a diff.")
    lines.append("")

    if advisory:
        lines.append("## Raised, but not acted on — your call")
        lines.append("")
        lines.append("Review flagged these and could not demonstrate them, or they conflicted "
                     "with a contract in the code. They were **not** repaired. An earlier version "
                     "of this workflow acted on reasoning alone and broke working code, so "
                     "anything unproven now comes to you instead.")
        lines.append("")
        for f in advisory:
            lines.append(_bullet(f))
            lines.append("  - Why not acted on: %s%s" % (
                f.get("gate", "unknown"),
                (" — " + f["gate_detail"]) if f.get("gate_detail") else ""))
            lines.append("")
        lines.append("")

    # --- the honest part ------------------------------------------------------------
    lines.append("## Still unproven")
    lines.append("")
    lines.append("- The review is one reviewer's reading of the requirements this feature should "
                 "meet. It is not a proof, and it does not cover requirements specific to your "
                 "product that are written down nowhere.")
    lines.append("- Only the tests shipped with the ticket were executed. No new regression test "
                 "was added for the repairs above, so a future change can undo them silently.")
    if final_list:
        lines.append("- The items still flagged above are the first thing to read.")
    lines.append("- The review names its findings freshly each pass, so this report cannot prove "
                 "a specific issue was fixed — only that it was not raised again.")
    lines.append("- Nothing here was run against production data, real concurrency, or real "
                 "upstream services.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("_Sandboxed run. No external action was taken and nothing was deployed._")
    return "\n".join(lines) + "\n"


def write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
